

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


public class TelaInicial extends javax.swing.JFrame {

    HashMap<String, Veiculo> veiculos = new HashMap<>();
    private PagamentoStrategy pagamentoStrategy;
    

    public boolean addVeiculo(Veiculo v) {
        veiculos.put(v.getNomeCondutor(), v);
        return true;
    }
    

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        setTitle("EasyParking Software");
       
    ImageIcon icon = new ImageIcon(getClass().getResource("/resources/trabalho.png")); 
    setIconImage(icon.getImage());
        vagasLabel.setText("20");
        pagamentoStrategy = pagamentoStrategy;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        visualizarButton = new javax.swing.JButton();
        preencherButton = new javax.swing.JButton();
        editarButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        vagasLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(450, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        visualizarButton.setText("Finalizar");
        visualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(visualizarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 150, -1));

        preencherButton.setText("Preencher Dados");
        preencherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preencherButtonActionPerformed(evt);
            }
        });
        getContentPane().add(preencherButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 150, -1));

        editarButton.setLabel("Editar Dados");
        editarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(editarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 150, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("Vagas Disponíveis:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        vagasLabel.setForeground(new java.awt.Color(242, 242, 242));
        vagasLabel.setText("jLabel3");
        getContentPane().add(vagasLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 25, 20));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 88, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fundoeasy.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 470, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void atualizaLabel(int novoValor) {
        vagasLabel.setText(Integer.toString(novoValor));
    }


    private void visualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarButtonActionPerformed
 if (veiculos.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Nenhum usuário cadastrado.");
    } else {
        Object[] possibleValues = veiculos.keySet().toArray();
        Object selectedValue = JOptionPane.showInputDialog(
            this, "Escolha o usuário", "Escolha", JOptionPane.INFORMATION_MESSAGE,
            null, possibleValues, possibleValues[0]);

        if (selectedValue != null) {
            // Pega o objeto carro que corresponde ao atual
            Veiculo carroSelecionado = veiculos.get(selectedValue.toString());

            PagamentoStrategy strategy;

            // Verifica o tipo de veículo e define a estratégia apropriada
            if (carroSelecionado instanceof Carro) {
                strategy = new CarroPagamentoStrategy();
            } else if (carroSelecionado instanceof Moto) {
                strategy = new MotoPagamentoStrategy();
            } else {
                // Caso padrão, defina uma estratégia padrão ou trate o erro de alguma forma
                strategy = null; // Defina a estratégia padrão ou trate o erro de outra forma
            }

            Visualizar visu = new Visualizar(veiculos, this, strategy);

              carroSelecionado.adicionarObservador(visu);

            
            visu.metodoVisualizar(
                carroSelecionado.getNomeCondutor(),
                carroSelecionado.getAutomovel(),
                carroSelecionado.getPlacaVeiculo(),
                carroSelecionado.getHoraEntrada()
            );

            visu.tempoUtilizado(carroSelecionado.getHoraEntrada());

            visu.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Nenhum usuário selecionado.");
        }
    }
    }//GEN-LAST:event_visualizarButtonActionPerformed

    private void preencherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preencherButtonActionPerformed
        CadastroVeiculo cadastro = new CadastroVeiculo(this);
        cadastro.setVisible(true);

    }//GEN-LAST:event_preencherButtonActionPerformed

    public String getLabel() {
        return vagasLabel.getText();
    }

    public void incrementLabel() {
        TelaInicial tela = TelaInicialSingleton.getInstance();
        System.out.println("Método incrementLabel foi chamado."); 
        System.out.println(tela.getLabel());
        String valorLabel = getLabel();
        int valorAtual = Integer.parseInt(valorLabel); 
        int novoValor = valorAtual + 1; 
        vagasLabel.setText(Integer.toString(novoValor)); 
    }

    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
        if (veiculos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nenhum usuário cadastrado.");
        } else {
            Object[] possibleValues = veiculos.keySet().toArray();
            Object selectedValue = JOptionPane.showInputDialog(
                    this, "Escolha o usuário", "Escolha", JOptionPane.INFORMATION_MESSAGE,
                    null, possibleValues, possibleValues[0]);
            if (selectedValue != null) {
                CadastroVeiculo c = new CadastroVeiculo(this, veiculos.get(selectedValue.toString()));
                c.setVisible(true);

            } else {
                JOptionPane.showMessageDialog(this, "Nenhum usuário selecionado.");
            }
        }
    }//GEN-LAST:event_editarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editarButton;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton preencherButton;
    public javax.swing.JLabel vagasLabel;
    private javax.swing.JButton visualizarButton;
    // End of variables declaration//GEN-END:variables

}

